### PR TITLE
Fix desync charactorvisitors and Caxton compatibility

### LINKED ISSUE #12: Advancement Menu Causes Game Freeze With Some  Advancements Visible
Original Report: https://github.com/keve1227/rubi/issues/16 by @Tahlpok

> Hi, first of all i wanted to thank you for your amazing mod, i'm glad someone took the time to give us such a material for learning Japanese while spending some time in Minecraft.
> 
> I noticed an issue with the Archievements. It works well when you have none or when you have only the first page (Stone Edge...) but once you go a bit further in the game. the game freeze if you go to the archievement menu.
> 
> I'm playing in 1.21 with rubi-1.04+1.21 and the furigana-v4+1.21-1.21.1 version.
> Switching off rubi fixes the crash. I assume one of the first succes of the game must create the issue with rubi
> 
> I don't know if it's a knowed issue.
> 
> Cheers

One example of such a crash causing advancement is minecraft:adventure/root.

Debugging has revealed this to be caused by the description trying to wrap but failing to do so because of two functions treating the ruby expression differently. This causes an infinite loop where no progress is made each iteration. In particular the function net.minecraft.client.font.TextHandler.LineWrappingCollector#collectLine does not result in the correct result.

### PR DESCRIPTION
**Pull request by Wetterquarz**
This pull request aims to fix #12 (https://github.com/keve1227/rubi/issues/16) and improve compatibility.

The fix of #12 has currently been achieved.
Compatibility (#1) has not been tested. Caxton is now compatible as of 5f80a30 (fix keve1227/furigana#3).

I have changed the architecture from "$^text(ruby)" converting to "\ue9c0text\ue9c1ruby\ue9c2" now replacing "$^text(ruby)" with a single character (\uFFFC) and then embedding the text and ruby in the net.minecraft.text.Style class.

As this is a major rewrite, there is currently still some differences in rendering which need to be fixed:
- [x] Ruby is displayed a few pixels lower than before in Above-mode (Fixed with 6f41c86)
- [x] Kanji are not equally spaced out in the gap but bunched in the middle (Fixed with 6f41c86)
- [x] Autocomplete suggestions are rendered too far left (Fixed with 4cf1f3f)

### CODE REVIEW

**Comment by keve1227** [comment]
I'm out of town for the weekend but I'm planning to take a closer look at this marvel on Tuesday 😁

File: src/main/java/com/kevinsundqvistnorlen/rubi/mixin/client/MixinTextHandler.java [hunk 1]
```diff
@@ -1,49 +1,63 @@
...
+import org.apache.commons.lang3.mutable.MutableFloat;
 import org.spongepowered.asm.mixin.*;
 import org.spongepowered.asm.mixin.injection.*;
 import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;
 
 @Mixin(TextHandler.class)
-public abstract class MixinTextHandler {
+public abstract class MixinTextHandler implements ITextHandler {
+    @Shadow @Final TextHandler.WidthRetriever widthRetriever;
+    @Unique private volatile boolean getWidthMutex = false;
```
Comment (keve1227) [inline src/main/java/com/kevinsundqvistnorlen/rubi/mixin/client/MixinTextHandler.java]: What does `getWidthMutex` do?

File: src/main/java/com/kevinsundqvistnorlen/rubi/mixin/client/MixinTextRenderer.java [hunk 2]
```diff
@@ -1,25 +1,23 @@
...
-    @Final
-    @Shadow
-    public int fontHeight;
-
-    @Final
-    @Shadow
-    private TextHandler handler;
+    @Final @Shadow public int fontHeight;
+    @Final @Shadow private TextHandler handler;
+    @Unique private boolean isSeparatingDrawCall = false;
```
Comment (keve1227) [inline src/main/java/com/kevinsundqvistnorlen/rubi/mixin/client/MixinTextRenderer.java]: `isSeparatingDrawCall` seems to be doing something similar to `getWidthMutex`. Are they related somehow?

**Review by keve1227 — COMMENTED** [review]
I marked `getWidthMutex` as volatile since I can't imagine any kind of "mutex" that wouldn't be. I'm just not sure what `getWidthMutex` and `isSeparatingDrawCall` are and if maybe they should both be marked volatile.

File: src/main/java/com/kevinsundqvistnorlen/rubi/mixin/client/MixinTextHandler.java (hunk 1 above)
Comment (Wetterquarz) [reply src/main/java/com/kevinsundqvistnorlen/rubi/mixin/client/MixinTextHandler.java]: getWidth() is injected in in order to split the call into multiple calls to getWidth() which then get summed together. In order to not get the infinite recursion because I always call the modified version of getWidth, I use getWidthMutex to ensure only calls to getWidth which come from outside get special treatment. And it does make sense to make it volatile but as this is in the rendering code, I would not actually expect multiple threads to access this.

File: src/main/java/com/kevinsundqvistnorlen/rubi/mixin/client/MixinTextRenderer.java (hunk 2 above)
Comment (Wetterquarz) [reply src/main/java/com/kevinsundqvistnorlen/rubi/mixin/client/MixinTextRenderer.java]: They are the same concept, just one is for getWidth() and the other for draw(). I agree, they should be named similarly

File: src/main/java/com/kevinsundqvistnorlen/rubi/mixin/client/MixinTextHandler.java (hunk 1 above)
Comment (keve1227) [reply src/main/java/com/kevinsundqvistnorlen/rubi/mixin/client/MixinTextHandler.java]: I accidentally removed the need for this since I removed the version of `RubyText.getWidth` that was calling `TextHandler.getWidth`.

Comment (Wetterquarz) [reply src/main/java/com/kevinsundqvistnorlen/rubi/mixin/client/MixinTextHandler.java]: The problem with calling the widthRetriever directly, which is only speculation, but Caxton seems to occasionally ignore the widthRetriever and do its own thing when using a custom font, which would then possibly cause discrepancies.

Comment (keve1227) [reply src/main/java/com/kevinsundqvistnorlen/rubi/mixin/client/MixinTextHandler.java]: That's tricky. Looking at Caxton's [source code](https://gitlab.com/Kyarei/caxton/-/blob/master/common/src/main/java/xyz/flirora/caxton/layout/CaxtonTextHandler.java?ref_type=heads#L87) it seems (on the surface) like they are using the vanilla width retriever, which Rubi now is modifying.

We might not even need to inject into the `getWidth` methods anymore. The fact that the code for `getWidth(OrderedText)` looks identical to the vanilla code is indicative of that. I will try removing them and see if Caxton works as expected.

Comment (Wetterquarz) [reply src/main/java/com/kevinsundqvistnorlen/rubi/mixin/client/MixinTextHandler.java]: With just the width retriever, is what I had, but that did not work with texture packs that replace your font to a caxton font. Maybe that was only because of the execution order which I only fixed later, so you would have to check that first.

**Comment by keve1227** [comment]
I must thank you for this. Using a single character per ruby and storing the details in the style is a really elegant solution to the line wrapping and overflow issues. If you feel this PR is ready, I'm happy to merge it.

> - [ ] Autocomplete suggestions are rendered too far left

I'm not entirely sure what this point is referring to. Has this been resolved?

File: src/main/java/com/kevinsundqvistnorlen/rubi/mixin/client/MixinTextHandler.java (hunk 1 above)
Comment (keve1227) [reply src/main/java/com/kevinsundqvistnorlen/rubi/mixin/client/MixinTextHandler.java]: I made it so that the text widths are calculated using the `TextHandler.getWidth` methods and not the width retriever directly, as in your original solution (5f80a30f8a29bdca76088a2dcc6e40b1db5c20d5). What I did remove is the version of `RubyText.getWith` that was using the width retriever since that's not compatible with Caxton. However, I left the width retriever implementation for compatibility with vanilla and other mods.

I also made the "recursion guards" (as I'm calling them) thread-local just in case. Threads A and B shouldn't have anything to do with each other's recursion guards.

**Comment by Wetterquarz** [comment]
> I must thank you for this. Using a single character per ruby and storing the details in the style is a really elegant solution to the line wrapping and overflow issues. If you feel this PR is ready, I'm happy to merge it.
> 
> > * [ ]  Autocomplete suggestions are rendered too far left
> 
> I'm not entirely sure what this point is referring to. Has this been resolved?

It is about the chat, where you can autocomplete names or parts of commands and ghosts of the suggestions is slightly shifted when not using Caxton. Unfortunately, it is still not fixed and have yet to find the source of the problem.

Edit: I just found the problem is more generally characters to the right of cursor are rendered to far left.

**Comment by Wetterquarz** [comment]
@keve1227, I believe it is now ready for merging.

**Comment by keve1227** [comment]
Now it's ready.

**Comment by Tahlpok** [comment]
Hey, I was abble to try it it worked ! Unfortunatly most of the mod are still stucked in 1.21.1 so i cannot play with the 1.21.3 mod.  Is there a way to lunch this mod in this version ? or do you think that you can also correct the bug in 1.21.1.

Thank you in advance !

**Comment by Wetterquarz** [comment]
> Hey, I was abble to try it it worked ! Unfortunatly most of the mod are still stucked in 1.21.1 so i cannot play with the 1.21.3 mod. Is there a way to lunch this mod in this version ? or do you think that you can also correct the bug in 1.21.1.
> 
> Thank you in advance !

I have started work on this and, except for a small problem which won't get in the way, it seems to work. This work can be seen in #18. You can also download the artifact from there.
